modLoader = "javafml"
loaderVersion = "[2,)"
license = "ARR"

[[mods]]
modId = "vidlib"
version = "${version}"
displayName = "VidLib"
authors = "latvian.dev"
logoFile = "vidlib_logo.png"
logoBlur = false

[[dependencies.vidlib]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.122,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vidlib]]
modId = "klib"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vidlib.mixins.json"