modLoader = "javafml"
loaderVersion = "[2,)"
license = "ARR"

[[mods]]
modId = "vidlib"
version = "${version}"
displayName = "VidLib"
authors = "latvian.dev"
logoFile = "vidlib_logo.png"
logoBlur = false

[[dependencies.vidlib]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vidlib]]
modId = "klib"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vidlib]]
modId = "imguiresources"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vidlib]]
modId = "flashback"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "vidlib.mixins.json"