modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
openGLVersion = "[3.2,)"

[[mods]]
modId = "vidlib"
version = "${version}"
displayName = "VidLib"
authors = "latvian.dev"
logoFile = "vidlib_logo.png"
logoBlur = false

[[dependencies.vidlib]]
modId = "neoforge"
type = "required"
versionRange = "[21.5.89,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vidlib]]
modId = "klib"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vidlib]]
modId = "imguiresources"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vidlib.mixins.json"