name: build
env:
  MAVEN_USERNAME: ${{ secrets.MBG_MAVEN_USERNAME }}
  MAVEN_TOKEN: ${{ secrets.MBG_MAVEN_TOKEN }}
  MAVEN_URL: ${{ secrets.MBG_MAVEN_URL }}
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [21]
        # and run on both Linux and Windows
        os: [ubuntu-latest, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
          check-latest: true
          cache: gradle
      - name: build
        run: gradle build
